version: '3.8'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn paintingstore_project.wsgi -b 0.0.0.0:8000
    environment:
      - env_var_name=${SECRET_KEY}
      - env_var_name=${DEBUG}
      - env_var_name=${STRIPE_TEST_PUBLISHABLE_KEY}
      - env_var_name=${STRIPE_TEST_SECRET_KEY}
      - env_var_name=${AWS_ACCESS_KEY_ID}
      - env_var_name=${AWS_SECRET_ACCESS_KEY}
      - env_var_name=${AWS_STORAGE_BUCKET_NAME}
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: