# Generated by Django 4.0.3 on 2022-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_alter_painting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artwork_type',
            field=models.CharField(default='painting', max_length=200),
        ),
    ]
